# Aliases to assets located on docker shared volumes
# last revision: 5-feb-2021
#
# file versioning in the filenames should always be updated
# to force a browser's cache to reset
location ~ ^/stylesheets/bootstrap.min.css {
    alias /opt/lib/bootstrap/bootstrap.min.css;
    add_header X-Content-Type-Options nosniff;
    expires 1y;
}
location ~ ^/stylesheets/bootstrap.min.css.map {
    alias /opt/lib/bootstrap/bootstrap.min.css.map;
    add_header X-Content-Type-Options nosniff;
    expires 1y;
}
location ~ ^/javascripts/bootstrap.min.js {
    alias /opt/lib/bootstrap/bootstrap.min.js;
    add_header X-Content-Type-Options nosniff;
    expires 1y;
}
# required by fontawesome
location ~ ^/javascripts/fontawesome-all.min.js {
    alias /opt/lib/fontawesomepro/js/all.min.js;
    add_header X-Content-Type-Options nosniff;
    expires 1y;
}
# required by bootstrap
location ~ ^/javascripts/jquery.slim.min.js {
    alias /opt/lib/bootstrap/jquery.slim.min.js;
    add_header X-Content-Type-Options nosniff;
    expires 1y;
}
# required by /upload
location ~ ^/javascripts/localforage.min.js {
    alias /opt/lib/upload/localforage.min.js;
    add_header X-Content-Type-Options nosniff;
    expires 1y;
}
# required by DOSee
location ~ ^/javascripts/browserfs.min.js {
    alias /opt/lib/dosee/browserfs.min.js;
    add_header X-Content-Type-Options nosniff;
    expires 1y;
}
location ~ ^/javascripts/browserfs-zipfs-extras.js {
    alias /opt/lib/dosee/browserfs-zipfs-extras.js;
    add_header X-Content-Type-Options nosniff;
    expires 1y;
}
location ~ ^/javascripts/clipboard.min.js {
    alias /opt/lib/dosee/clipboard.min.js;
    add_header X-Content-Type-Options nosniff;
    expires 1y;
}
location ~ ^/javascripts/es6-promise.min.js {
    alias /opt/lib/dosee/es6-promise.min.js;
    add_header X-Content-Type-Options nosniff;
    expires 1y;
}
location ~ ^/javascripts/FileSaver.min.js {
    alias /opt/lib/dosee/FileSaver.min.js;
    add_header X-Content-Type-Options nosniff;
    expires 1y;
}
location ~ ^/javascripts/screenfull.js {
    alias /opt/lib/dosee/screenfull.js;
    add_header X-Content-Type-Options nosniff;
    expires 1y;
}
# infinite scrolling
location ~ ^/javascripts/infinite-scroll.pkgd.min.js {
    alias /opt/lib/frontend/infinite-scroll.pkgd.min.js;
    add_header X-Content-Type-Options nosniff;
    expires 1y;
}
# chart.js
location ~ ^/javascripts/chart.min.js {
    alias /opt/lib/frontend/chart.min.js;
    add_header X-Content-Type-Options nosniff;
    expires 1y;
}
# chart.js dependency
location ~ ^/javascripts/moment.min.js {
    alias /opt/lib/frontend/moment.min.js;
    add_header X-Content-Type-Options nosniff;
    expires 1y;
}
# choices.js
location ~ ^/javascripts/choices.min.js {
    alias /opt/lib/choices/choices.min.js;
    add_header X-Content-Type-Options nosniff;
    expires 1y;
}
location ~ ^/stylesheets/base.min.css {
    alias /opt/lib/choices/base.min.css;
    add_header X-Content-Type-Options nosniff;
    expires 1y;
}
location ~ ^/stylesheets/choices.min.css {
    alias /opt/lib/choices/choices.min.css;
    add_header X-Content-Type-Options nosniff;
    expires 1y;
}
# headroom, hide your header on scroll
location ~ ^/javascripts/headroom.min.js {
    alias /opt/lib/frontend/headroom.min.js;
    add_header X-Content-Type-Options nosniff;
    expires 1y;
}
# lite yt (youtube)
location ~ ^/javascripts/lite-yt-embed.min.js {
    alias /opt/lib/frontend/lite-yt-embed.min.js;
    add_header X-Content-Type-Options nosniff;
    expires 1y;
}
location ~ ^/javascripts/lite-yt-embed.min.css {
    alias /opt/lib/frontend/lite-yt-embed.min.css;
    add_header X-Content-Type-Options nosniff;
    expires 1y;
}