# Index for the Lucee/Tomcat configurations while testing
# last revision: 29-jul-2019
#
# Proxy settings
proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=default:10m inactive=24h max_size=100m;
proxy_temp_path /var/cache/nginx/tmp;
# HTTP server settings
server {
    listen 8560 default_server;
    server_name _;
#    autoindex on;
    root /var/www;
    server_name_in_redirect off;
# aliases.conf needs to be placed here at the top of this server config
    include conf.d/lucee_admin.conf;
    include conf.d/aliases.conf;
    include conf.d/rewrite.conf;
    include conf.d/locations.conf;
    include conf.d/legacy.conf;
}
# Custom nginx error pages
error_page 403 404 =404 /system/notfound;
# Server settings
keepalive_timeout 20s;
open_file_cache max=100 inactive=60;
open_file_cache_errors on;
sendfile on;
sendfile_max_chunk 0;
server_tokens off;
tcp_nodelay on;
tcp_nopush on;
# client_max_body_size disabled to allow user file uploads
client_max_body_size 0;
