# HTTP response status codes
# https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
#
# Cfwheels redirections
# (root redirection is found in locations.conf)
#
location ~ ^/welcome {
    return 301 $scheme://$host/home;
}
# Legacy file downloads, used by Pouet and Demozoo
location ~ ^/file/download/?(.*)$ {
    return 307 $scheme://$host/d/$1;
}
# Legacy URL redirections
#
location = /apollo-x/fc.htm {
    return 301 $scheme://$host/wayback/apollo-x-demo-resources-1999-december-17/fc.htm;
}
location = /bbs.cfm {
    return 301 $scheme://$host/organisation/list/bbs;
}
location = /contact.cfm {
    return 301 $scheme://$host/contact;
}
location = /cracktros.cfm {
    return 301 $scheme://$host/file/list/intro;
}
# Pouet wrong linkage correction
# http://www.defacto2.net/cracktros-detail.cfm?type=file&value=skillion1
location = /cracktros-detail.cfm {
    return 301 $scheme://$host/search/result?search=files&query=$arg_value;
}
location = /documents.cfm {
    return 301 $scheme://$host/file/list/document;
}
location = /groups.cfm {
    return 301 $scheme://$host/organisation/list;
}
location = /includes/documentsweb/df2web99/scene-archive/history.html {
    return 301 $scheme://$host/wayback/defacto2-from-1999-september-26/scene-archive/history.html;
}
location = /includes/documentsweb/tKC_history.html {
    return 301 $scheme://$host/wayback/the-life-and-legend-of-tkc-2000-october-10/index.html;
}
location ~ ^/legacy/apollo-x/?(.*)$ {
    return 301 $scheme://$host/wayback/apollo-x-demo-resources-1999-december-17/$1;
}
location = /magazines.cfm {
    return 301 $scheme://$host/file/list/magazine;
}
location = /nfo-files.cfm {
    return 301 $scheme://$host/file/list/nfotool;
}
location = /portal.cfm {
    return 301 $scheme://$host/link/list;
}
location ~ ^/scene-archive/?$ {
    return 301 $scheme://$host/;
}
location ~ ^/scene-news/?(.*)$ {
    return 301 $scheme://$host/wayback/the-scene-news-from-1999-september-14/$1;
}
location = /site-info.cfm {
    return 301 $scheme://$host/defacto2;
}
location = /web/20120827022026/http:/www.defacto2.net:80/file/list/nfotool {
    return 301 $scheme://$host/file/list/nfotool;
}
location = /web.pages/warez_world-1.htm {
    return 301 $scheme://$host/wayback/warez-world-from-2001-july-26/index.html;
}
