# Hide possible CFML file identifiers
location ~* ^/(application.cfc|index.cfm|rewrite.cfm|root.cfm)$ {
    return 404;
}
# Hide possible CFML directory identifiers
location ~* ^(/(config|controllers|events|models|plugins|views|web-inf|wheels)/?(.*))$ {
    return 404;
}
# Serve atom, & rss
# these are legacy placeholders, they maybe removed in the future
location ~ ^/(files/xml/(\.atom|.rss))$ {
    add_header Cache-Control "public";
    access_log off;
    expires 1y;
}
# Serve static directories
location ~ ^/(files|images|javascript|stylesheets)/ {
    add_header X-Content-Type-Options nosniff;
    add_header Cache-Control "public";
    access_log off;
    expires 1y;
}
# Serve static files in ROOT, these never change
location ~ \.(htm|html|txt|xml)$ {
    add_header X-Content-Type-Options nosniff;
    add_header Cache-Control "public";
    access_log off;
    expires 1y;
}
# Uncaught static files
location ~*  \.min.(js|css)$ {
    add_header X-Content-Type-Options nosniff;
    add_header Cache-Control "public";
    access_log off;
    expires 1y;
}
location ~* \.(js|css)$ {
    add_header X-Content-Type-Options nosniff;
    add_header Cache-Control "public";
    access_log off;
    expires 1y;
}
# Lucee dynamic content entry point
location / {
    index index.cfm;
    try_files $uri $uri/ @rules;
}
# Redirect root URLs otherwise nginx will return a 404
location = / {
    return 301 $scheme://$host/home;
}

# HTML3 dynamic content entry point
location ~ ^/html3 {
    index index.cfm;
    try_files $uri $uri/ @rules;
}
# hosted historical websites entry point
location ~ ^/wayback {
    index index.htm index.html;
    autoindex on;
    expires 1y;
}
location ~ ^/wayback/?(.*)\.(txt)$ {
    expires 1y;
}
# Lucee heartbeat for Docker Compose
location = /status.cfm {
    proxy_set_header X-Forwarded-For     $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto   $scheme;
    proxy_set_header X-Real-IP           $remote_addr;
    proxy_set_header Host                $http_host;
    proxy_redirect off;
    proxy_pass http://10.138.42.159:8888;
}
