# Lucee protections
# last revision: 6-aug-2019
#
# block and ignore requests for /lucee/admin/...
location ~ ^/lucee/ {
    return 404;
}
#block/ignore requests for Application.cfc/cfm
location ~* Application.cf[mc]$ {
    return 404;
}
