# Proxy rules and headers for testing
# last revision: 15-jan-2019
#
location @rules {
# CfWheels rewrite
    rewrite ^(.*)$ /rewrite.cfm$1;
}
location /rewrite.cfm {
# Standard reverse proxy
    proxy_redirect off;
    proxy_connect_timeout 75s;
    proxy_read_timeout 2m;
    proxy_send_timeout 2m;
    proxy_pass http://10.138.42.159:8888;
# Standard headers
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Port $server_port;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Host $http_host;
# Custom headers
    proxy_set_header X-Nginx-Version $nginx_version;
    proxy_set_header X-Host-Time $time_iso8601;
# Security features
# See for more details https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers
# https://scotthelme.co.uk/hardening-your-http-response-headers/
    add_header Strict-Transport-Security "max-age=63072000; includeSubdomains";
    add_header X-Frame-Options DENY;
    add_header X-Content-Type-Options nosniff;
    add_header X-Xss-Protection "1; mode=block" always;
#
# Content Security Policy
# Is set in /opt/www_proxy/configs/defacto2.net.conf
#
# Nginx static files cache
# Is located at on the host server /var/cache/nginx
#
# Reverse proxy cache
    add_header X-Cache-Status $upstream_cache_status;
    proxy_cache default;
    proxy_cache_lock on;
    proxy_cache_use_stale updating;
# Allow file transfers larger than 1G
# https://www.scalescale.com/tips/nginx/optimizing-nginx-for-serving-files-bigger-than-1gb/
#    proxy_max_temp_file_size 2886m;
    proxy_max_temp_file_size 0;
}
